server:
  port: 8081
  servlet:
    contextPath: /movie-rental-service

com.etraveli.movie.rental:
  rentalFee:
    - movieCode: REGULAR
      startingFee: 2
      startingFeeEligibleDays: 2
      dailyFee: 1.5

    - movieCode: NEW
      startingFee: 3
      startingFeeEligibleDays: 0
      additionalDailyFee: 0

    - movieCode: CHILDREN
      startingFee: 1.5
      startingFeeEligibleDays: 3
      additionalDailyFee: 1.5
